# -*- coding: utf-8 -*-
"""DAY3-SINGAPORE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJyN45BGCIeUyT0EQ50838O4UX6Afr3c
"""

#THE FIZZBUZZ PROBLEM.

for i in range(1,101):
    if (i%3 == 0) and (i%5 == 0):
        print("fizzbuzz")
    elif (i%3 == 0):
        print("fizz")
    elif (i%5 == 0):
        print("buzz")
    else:
        print(i)

#PRINT FIRST N NATURAL NO. ACC TO INPUT N BY USER.

n = int(input('Enter n: '))
for i in range(n):
    print(i+1)

#TABLE OF 5,6,7,8,9,10

for i in range(5,11):
    print()
    print('Table for {}'.format(i))
    for j in range(11):
        print('{} x {} = {}'.format(i,j,i*j))

