# -*- coding: utf-8 -*-
"""DAY 4-NEWZEALAND

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rG45SHGDnMnNprVO95FGuj4KSLFcABP9
"""

#find second largest element in array.

import math

a = [11,13,23,10,55]

large = -math.inf
slarge = -math.inf

for i in a:
    if i >= large:
        large = i
        
for i in a:
    if (i >= slarge) and (i < large):
        slarge = i

print(large)
print(slarge)

# seperate odd and even no. and print them seperately.

a = []
even_nos = []
odd_nos = []

n = int(input('Enter count of numbers: '))

for i in range(n):
    a.append(int(input('Enter number {}: '.format(i+1))))
    if a[i]%2 == 0:
        even_nos.append(a[i])
    else:
        odd_nos.append(a[i])
           
print('Even numbers: ', even_nos)
print('Odd numbers: ', odd_nos)

#find sum of digits of a no.

n = input('Please enter number: ')

a = str(n)
b = len(a)
sum = 0

for i in range(b):
    sum += int(a[i])

print('Sum of digits: ',sum)

#loan EMI CALCULATOR.

print('EMI Loan Calculator')
print()

p = float(input('Please enter principal amount: '))
i = float(input('Please enter annual interest rate in %: '))
t = float(input('Please enter tenure in years: '))

n = t*12
r = (i/(12*100))
e = (p*r*((1+r)**n)) / (((1+r)**n)-1)

print()
print('EMI: ', e)
print('Principal Amount: ', p)
print('Interest Amount: ', (e*n)-p)
print('Total Payable: ', e*n)

#BANKING SYSTEM

print('Banking System')
print()

accounts = {'043': ['PRANIT MALIK', 100]}

print('Select activity from list')
print('1: Add account for new user')
print('2: Add money to account')
print('3: Withdraw money from account')
print('4: Display balance')
print()

a = int(input('Enter Selection: '))
print()

if a == 1:
    print('You have selected the option to add account for aa new user')
    b = input('Please provide customer id: ')
    c = input('Please provide customer name (Firstname Lastname): ')
    accounts[b] = [c, 0]
    print('New Account created for customer id ',b)    
elif a == 2:
    print('You have selected the option to add money to account')
    d = input('Please provide customer id: ')
    e = float(input('Please enter amount to be added to account: '))
    accounts[d][1] += e
    print('Amount added')
    print('New Balance: ',accounts[d][1])
elif a == 3:
    print('You have selected the option to withdraw money from account')
    f = input('Please provide customer id: ')
    g = float(input('Please enter amount to be added to account'))
    if (accounts[f][1] >= g):
        accounts[f][1] -= g
        print('Amount withdrawn')
        print('New Balance: ',accounts[f][1])
    else:
        print('Not enough balance in the account')
elif a == 4:
    print('You have selected the option to view balance')
    h = input('Please provide customer id: ')
    print('Account Balance is: ',accounts[h][1])
elif a == 5:
    print('You have selected Beverage')
else:
    print('Invalid Selection')

#SCHOOL SYSTEM

print('School System')
print()

database = {'043': ['PRANIT MALIK','10','B'], '105': ['ANMOL','12','B'], '109': ["NAVED", '12','B']}

print('Select activity from list')
print('1: Add new student to a class')
print('2: Show total number of students in a class')
print('3: Remove the name of a student from a class')
print('4: Promote a student to the next class')
print()

a = int(input('Enter Selection: '))
print()

if a == 1:
    print('You have selected the option to add a new student to a class')
    b = input('Please provide student id: ')
    c = input('Please provide student name (Firstname Lastname): ')
    d = input('Please provide standard: ')
    e = input('Please enter division: ')
    database[b] = [c, d, e]
    print('Student added')
    print()
    print(database)
elif a == 2:
    print('You have selected the option to show the total number of students in a class')
    f = input('Please provide standard: ')
    g = input('Please enter division: ')
    count = 0
    for i,j in database.items():
        if (j[1] == f) and (j[2] == g):
            count += 1
    print('There are {} students in class {}{}'.format(count, f, g))
elif a == 3:
    print('You have selected the option to remove a student from the class')
    h = input('Please provide student id: ')
    database.pop(h)
    print('Student removed')
    print()
    print(database)
elif a == 4:
    print('You have selected the option to promote a student to the next class')
    i = input('Please provide student id: ')
    if int(database[i][1]) >= 12:
        print('Not possible as there is no grade after 12th')
    else:
        database[i][1] = int(database[i][1])
        database[i][1] += 1
        database[i][1] = str(database[i][1])
        print('Student promoted')
    print()
    print(database)
else:
    print('Invalid Selection')

